sudo: true
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

script:
   - mvn clean compile package -DskipTests=true

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')